---
- name: add firewall rules
  firewalld:
    permanent: "{{ item.permanent | default(true) }}"
    port: "{{ item.port }}"
    state: "{{ item.state | default('enabled') }}"
    zone: "{{ item.zone | default('public') }}"
  loop: "{{ firewall_ports }}"
  notify: "firewalld reload"
  tags: firewalld

- name: template {{ steam_appid }} service files

- name: set admin list


